title: clij-advanced-filters
logo: /images/clijx_logo.png
description: CLIJx: THe incubator for CLIJ2 (experimental)
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
plugins:
  - jekyll-redirect-from
